#!/bin/bash
#
# setup_daily_fetch.sh — Install a macOS launchd job to auto-fetch
# daily MLB data and push to GitHub.
#
# Usage:
#   cd /path/to/mlb-nsfi-model
#   chmod +x setup_daily_fetch.sh
#   ./setup_daily_fetch.sh
#
# To uninstall:
#   launchctl unload ~/Library/LaunchAgents/com.mlb-nsfi.fetch-daily.plist
#   rm ~/Library/LaunchAgents/com.mlb-nsfi.fetch-daily.plist
#   rm ~/bin/mlb-nsfi-fetch.sh

set -e

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
VENV_DIR="$REPO_DIR/.venv"
SCRIPT_PATH="$HOME/bin/mlb-nsfi-fetch.sh"
PLIST_PATH="$HOME/Library/LaunchAgents/com.mlb-nsfi.fetch-daily.plist"
LOG_PATH="$HOME/Library/Logs/mlb-nsfi-fetch.log"

echo "Setting up MLB NSFI daily fetch..."
echo "  Repo: $REPO_DIR"

# ── 0. Create venv if it doesn't exist ────────────────────────────────────────

if [ ! -d "$VENV_DIR" ]; then
    echo "  Creating Python virtual environment..."
    python3 -m venv "$VENV_DIR"
fi
echo "  Installing/updating dependencies..."
"$VENV_DIR/bin/pip" install --quiet --upgrade requests
echo "  Installed dependencies."

# ── 1. Create the fetch script ───────────────────────────────────────────────

mkdir -p "$HOME/bin"

cat > "$SCRIPT_PATH" << FETCHSCRIPT
#!/bin/bash
# Auto-generated by setup_daily_fetch.sh
# Fetches today's MLB data + DK odds, commits and pushes to GitHub.

LOG="$LOG_PATH"
REPO="$REPO_DIR"
DATE=\$(date +%Y-%m-%d)
DATEFILE=\$(date +%Y%m%d)

echo "[\$(date)] Starting daily fetch for \$DATE" >> "\$LOG"

cd "\$REPO" || { echo "[\$(date)] ERROR: Cannot cd to \$REPO" >> "\$LOG"; exit 1; }

# Use the venv Python
PYTHON="\$REPO/.venv/bin/python3"

# Fetch data
"\$PYTHON" fetch_daily.py >> "\$LOG" 2>&1

# Commit and push if the file exists and has changes
if [ -f "daily_\${DATEFILE}.json" ]; then
    git add "daily_\${DATEFILE}.json"
    if ! git diff --cached --quiet; then
        git commit -m "Auto-fetch daily data for \${DATE}" >> "\$LOG" 2>&1
        git push >> "\$LOG" 2>&1
        echo "[\$(date)] Pushed daily_\${DATEFILE}.json" >> "\$LOG"
    else
        echo "[\$(date)] No changes to commit" >> "\$LOG"
    fi
else
    echo "[\$(date)] WARNING: daily_\${DATEFILE}.json not found" >> "\$LOG"
fi

echo "[\$(date)] Done" >> "\$LOG"
echo "" >> "\$LOG"
FETCHSCRIPT

chmod +x "$SCRIPT_PATH"
echo "  Created fetch script: $SCRIPT_PATH"

# ── 2. Create the launchd plist ──────────────────────────────────────────────

mkdir -p "$HOME/Library/LaunchAgents"

cat > "$PLIST_PATH" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.mlb-nsfi.fetch-daily</string>

    <key>ProgramArguments</key>
    <array>
        <string>${SCRIPT_PATH}</string>
    </array>

    <!-- Run at 1:00 PM ET and 5:30 PM ET daily during MLB season -->
    <key>StartCalendarInterval</key>
    <array>
        <dict>
            <key>Hour</key>
            <integer>13</integer>
            <key>Minute</key>
            <integer>0</integer>
        </dict>
        <dict>
            <key>Hour</key>
            <integer>17</integer>
            <key>Minute</key>
            <integer>30</integer>
        </dict>
    </array>

    <key>StandardOutPath</key>
    <string>${LOG_PATH}</string>
    <key>StandardErrorPath</key>
    <string>${LOG_PATH}</string>
</dict>
</plist>
PLIST

echo "  Created launchd plist: $PLIST_PATH"

# ── 3. Load the job ──────────────────────────────────────────────────────────

# Unload first if already loaded
launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load "$PLIST_PATH"

echo "  Loaded launchd job."
echo ""
echo "Done! Daily fetch will run at 1:00 PM and 5:30 PM (your local time)."
echo ""
echo "Useful commands:"
echo "  Check logs:    tail -f $LOG_PATH"
echo "  Run manually:  $SCRIPT_PATH"
echo "  Uninstall:     launchctl unload $PLIST_PATH && rm $PLIST_PATH $SCRIPT_PATH"
